apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chitra-ns
  name: petshop
spec:
  selector:
    matchLabels:
      app: petshop
  replicas: 1 
  template: 
    metadata:
      labels:
        app: petshop
    spec:
      containers:
      - name: petshop
        image: 562041613760.dkr.ecr.ap-south-1.amazonaws.com/chitra-petstore:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: chitra-ns
  name: petshop
spec:
  type: LoadBalancer
  selector:
    app: petshop
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
